using CineNote.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CineNote.Services
{
    public static class MovieCatalog
    {
        private static readonly List<Movie> _movies = new List<Movie>
        {
            new Movie { Title = "The Shawshank Redemption", Genre = "Drama" },
            new Movie { Title = "The Godfather",            Genre = "Drama" },
            new Movie { Title = "The Dark Knight",          Genre = "Action" },
            new Movie { Title = "Pulp Fiction",             Genre = "Crime"  },
            new Movie { Title = "Parasite",                 Genre = "Thriller"},
            new Movie { Title = "Inception",                Genre = "Sci‑Fi" },
            new Movie { Title = "Spirited Away",            Genre = "Fantasy"},
            new Movie { Title = "Get Out",                  Genre = "Horror" },
            new Movie { Title = "Amélie",                   Genre = "Romance"},
            new Movie { Title = "Toy Story",                Genre = "Comedy" },
            new Movie { Title = "The Grand Budapest Hotel",  Genre = "Comedy" },
            new Movie { Title = "Interstellar",              Genre = "Sci‑Fi" },
            new Movie { Title = "A Ghost Story",             Genre = "Drama" },
            new Movie { Title = "Whiplash",                 Genre = "Drama" },
            new Movie { Title = "Her",                       Genre = "Romance" },
            new Movie { Title = "Moonlight",                 Genre = "Drama" },
            new Movie { Title = "The Revenant",              Genre = "Adventure" },
            new Movie { Title = "The Prestige",              Genre = "Thriller" },
            new Movie { Title = "Blade Runner 2049",         Genre = "Sci‑Fi" },
            new Movie { Title = "The Big Lebowski",          Genre = "Comedy" },
            new Movie { Title = "The Witch",                 Genre = "Horror" },
            new Movie { Title = "Ex Machina",               Genre = "Sci‑Fi" },
            new Movie { Title = "Children of Men",           Genre = "Thriller" },
            new Movie { Title = "Drive",                     Genre = "Crime" },
            new Movie { Title = "Hereditary",                Genre = "Horror" },
            new Movie { Title = "Lady Bird",                 Genre = "Drama" },
            new Movie { Title = "The Handmaiden",            Genre = "Thriller" },
            new Movie { Title = "La La Land",                Genre = "Romance" },
            new Movie { Title = "Coco",                      Genre = "Animation" },
            new Movie { Title = "The Lighthouse",            Genre = "Horror" },
            new Movie { Title = "Arrival",                   Genre = "Sci‑Fi" },
            new Movie { Title = "Memento",                   Genre = "Thriller" },
            new Movie { Title = "Goodfellas",                Genre = "Crime" },
            new Movie { Title = "Raging Bull",               Genre = "Drama" },
            new Movie { Title = "The Social Network",        Genre = "Drama" },
            new Movie { Title = "Moonrise Kingdom",          Genre = "Comedy" },
            new Movie { Title = "The King's Speech",         Genre = "Drama" },
            new Movie { Title = "The Secret Life of Walter Mitty", Genre = "Adventure" },
            new Movie { Title = "Her",                       Genre = "Romance" },
            new Movie { Title = "Shutter Island",            Genre = "Thriller" },
            new Movie { Title = "Borat",                     Genre = "Comedy" },
            new Movie { Title = "The Martian",               Genre = "Sci‑Fi" },
            new Movie { Title = "Sicario",                   Genre = "Thriller" },
            new Movie { Title = "A Quiet Place",             Genre = "Horror" },
            new Movie { Title = "The Favourite",             Genre = "Drama" },
            new Movie { Title = "The Tree of Life",          Genre = "Drama" },
            new Movie { Title = "The Pursuit of Happyness",  Genre = "Drama" },
            new Movie { Title = "The Zookeeper's Wife",      Genre = "Drama" },
            new Movie { Title = "Prisoners",                Genre = "Thriller" },
            new Movie { Title = "The Shape of Water",       Genre = "Fantasy" },
            new Movie { Title = "The Pianist",              Genre = "Drama" },
            new Movie { Title = "Lady Vengeance",           Genre = "Thriller" },
            new Movie { Title = "The Road",                 Genre = "Drama" },
            new Movie { Title = "Requiem for a Dream",      Genre = "Drama" },
            new Movie { Title = "The Fighter",              Genre = "Drama" },
            new Movie { Title = "Anomalisa",                Genre = "Animation" },
            new Movie { Title = "The Babadook",             Genre = "Horror" },
            new Movie { Title = "Moon",                     Genre = "Sci‑Fi" },
            new Movie { Title = "The Secret Window",        Genre = "Thriller" },
            new Movie { Title = "Tinker Tailor Soldier Spy", Genre = "Thriller" },
            new Movie { Title = "A Separation",             Genre = "Drama" },
            new Movie { Title = "The Talented Mr. Ripley",  Genre = "Thriller" },
            new Movie { Title = "A Beautiful Mind",         Genre = "Drama" },
            new Movie { Title = "The Lobster",              Genre = "Comedy" },
            new Movie { Title = "The Invisible Man",        Genre = "Horror" },
            new Movie { Title = "The Hunt",                 Genre = "Drama" },
            new Movie { Title = "Under the Skin",           Genre = "Sci‑Fi" },
            new Movie { Title = "The Descendants",          Genre = "Drama" },
            new Movie { Title = "Midnight in Paris",        Genre = "Comedy" },
            new Movie { Title = "The Killing of a Sacred Deer", Genre = "Thriller" },
            new Movie { Title = "Donnie Darko",             Genre = "Sci‑Fi" },
            new Movie { Title = "The Artist",               Genre = "Drama" },
            new Movie { Title = "The Place Beyond the Pines", Genre = "Drama" },
            new Movie { Title = "No Country for Old Men",   Genre = "Thriller" },
            new Movie { Title = "Black Swan",               Genre = "Thriller" },
            new Movie { Title = "The Witch",                Genre = "Horror" },
            new Movie { Title = "The Edge of Tomorrow",     Genre = "Sci‑Fi" },
            new Movie { Title = "Babel",                    Genre = "Drama" },
            new Movie { Title = "Hunger",                   Genre = "Drama" },
            new Movie { Title = "12 Years a Slave",         Genre = "Drama" },
            new Movie { Title = "The Revenant",             Genre = "Adventure" },
            new Movie { Title = "The Big Short",            Genre = "Drama" },
            new Movie { Title = "Lost in Translation",      Genre = "Drama" },
            new Movie { Title = "The Andromeda Strain",     Genre = "Sci‑Fi" },
            new Movie { Title = "The Curious Case of Benjamin Button", Genre = "Drama" },
            new Movie { Title = "Good Will Hunting",        Genre = "Drama" },
            new Movie { Title = "The Maze Runner",          Genre = "Sci‑Fi" },
            new Movie { Title = "It Follows",               Genre = "Horror" },
            new Movie { Title = "Eternal Sunshine of the Spotless Mind", Genre = "Romance" },
            new Movie { Title = "The Martian",              Genre = "Sci‑Fi" },
            new Movie { Title = "The French Dispatch",      Genre = "Comedy" },
            new Movie { Title = "Trollhunter",              Genre = "Fantasy" },
            new Movie { Title = "The Queen",                Genre = "Drama" },
            new Movie { Title = "The Imitation Game",       Genre = "Drama" },
            new Movie { Title = "Gangs of New York",        Genre = "Drama" },
            new Movie { Title = "The Forever Purge",        Genre = "Horror" },
            new Movie { Title = "Oldboy",                   Genre = "Thriller" },
            new Movie { Title = "The Wind That Shakes the Barley", Genre = "Drama" },
            new Movie { Title = "Fantastic Mr. Fox",        Genre = "Animation" },
            new Movie { Title = "Stardust",                 Genre = "Fantasy" },
            new Movie { Title = "Snowpiercer",              Genre = "Sci‑Fi" },
            new Movie { Title = "The Night Manager",        Genre = "Thriller" },
            new Movie { Title = "Mystic River",             Genre = "Drama" },
            new Movie { Title = "The House That Jack Built", Genre = "Thriller" },
            new Movie { Title = "The Dark Knight Rises",    Genre = "Action" },
            new Movie { Title = "My Neighbor Totoro",       Genre = "Animation" }

        };

        public static List<Movie> All() => new List<Movie>(_movies);
    }
}
